-- MySQL Script generated by MySQL Workbench
-- 05/01/15 18:03:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema machiavel_fantasy
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema machiavel_fantasy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `machiavel_fantasy` DEFAULT CHARACTER SET utf8 ;
USE `machiavel_fantasy` ;

-- -----------------------------------------------------
-- Table `machiavel_fantasy`.`club`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `machiavel_fantasy`.`club` ;

CREATE TABLE IF NOT EXISTS `machiavel_fantasy`.`club` (
  `text_club` LONGTEXT NOT NULL,
  `date_update` DATETIME NOT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machiavel_fantasy`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `machiavel_fantasy`.`users` ;

CREATE TABLE IF NOT EXISTS `machiavel_fantasy`.`users` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(35) NOT NULL,
  `civility` VARCHAR(4) NOT NULL,
  `lastname` VARCHAR(35) NOT NULL,
  `firstname` VARCHAR(35) NOT NULL,
  `password` VARCHAR(60) NOT NULL,
  `email` VARCHAR(320) NOT NULL,
  `date_register` DATETIME NOT NULL,
  `date_lastco` DATETIME NOT NULL,
  `ip_user` VARCHAR(15) NOT NULL,
  `key_user` VARCHAR(100) NOT NULL,
  `avatars` VARCHAR(255) NOT NULL DEFAULT 'defaut.png',
  `activation` INT(1) NOT NULL DEFAULT '0',
  `droits` INT(1) NOT NULL DEFAULT '1' COMMENT '0 = aucun droit ; 1 = utilisateur ; 2 = modérateur ; 3 = administrateur',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machiavel_fantasy`.`type_jeu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `machiavel_fantasy`.`type_jeu` ;

CREATE TABLE IF NOT EXISTS `machiavel_fantasy`.`type_jeu` (
  `id_type_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `libelle_type_jeu` VARCHAR(50) NOT NULL,
  `description_type_jeu` VARCHAR(300) NOT NULL,
  `image_type_jeu` VARCHAR(200) NOT NULL,
  `color_type_jeu` VARCHAR(10) NOT NULL,
  `icon_type_jeu` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_type_jeu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machiavel_fantasy`.`jeu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `machiavel_fantasy`.`jeu` ;

CREATE TABLE IF NOT EXISTS `machiavel_fantasy`.`jeu` (
  `id_jeu` INT(11) NOT NULL AUTO_INCREMENT,
  `title_jeu` VARCHAR(50) NOT NULL,
  `text_jeu` LONGTEXT NOT NULL,
  `image_jeu` VARCHAR(200) NOT NULL DEFAULT 'defaut_jeu.png',
  `date_update` DATETIME NOT NULL,
  `statut_jeu` INT(11) NOT NULL DEFAULT '1',
  `id_user` INT(11) NOT NULL,
  `id_type_jeu` INT(11) NOT NULL,
  PRIMARY KEY (`id_jeu`),
  INDEX `fk_jeu_type_jeu1_idx` (`id_type_jeu` ASC),
  INDEX `fk_jeu_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_jeu_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `machiavel_fantasy`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_jeu_type_jeu1`
    FOREIGN KEY (`id_type_jeu`)
    REFERENCES `machiavel_fantasy`.`type_jeu` (`id_type_jeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `machiavel_fantasy`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `machiavel_fantasy`.`event` ;

CREATE TABLE IF NOT EXISTS `machiavel_fantasy`.`event` (
  `id_event` INT(11) NOT NULL AUTO_INCREMENT,
  `title_event` VARCHAR(50) NOT NULL,
  `text_event` TEXT NOT NULL,
  `image_event` VARCHAR(200) NOT NULL DEFAULT 'defaut_event.png',
  `date_event` DATETIME NOT NULL,
  `date_update` DATETIME NOT NULL,
  `statut_event` INT(11) NOT NULL DEFAULT '1',
  `id_user` INT(11) NOT NULL,
  `id_jeu` INT(11) NOT NULL,
  PRIMARY KEY (`id_event`),
  INDEX `fk_event_jeu1_idx` (`id_jeu` ASC),
  INDEX `fk_event_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_event_jeu1`
    FOREIGN KEY (`id_jeu`)
    REFERENCES `machiavel_fantasy`.`jeu` (`id_jeu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `machiavel_fantasy`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
